window.LIFEHUB_DATA = window.LIFEHUB_DATA || {};
window.LIFEHUB_DATA.cards = [
  {
    title: "Inbox",
    description:
      "Temporary landing zone for files coming out of Downloads. Clear this every Friday before logging off.",
    links: [{ label: "Open Inbox", href: "Inbox", note: "Review & file everything" }],
    tags: ["weekly", "triage"],
    focus: "Keep empty by Friday",
    root: "Inbox",
    icon: "inbox",
  },
  {
    title: "Work",
    description: "Employment history, contracts, interview prep and upskilling records.",
    links: [
      { label: "Career files & contracts", href: "Work/Career" },
      { label: "Job search material", href: "Work/Job_Search" },
      { label: "Professional development", href: "Work/Professional_Development" },
    ],
    tags: ["career", "upskilling"],
    focus: "Contracts, interviews, learning",
    root: "Work",
    icon: "briefcase",
  },
  {
    title: "Family",
    description: "Medical records, therapy research, school paperwork.",
    links: [
      { label: "Health & medical", href: "Family/Health" },
      { label: "Education & therapy resources", href: "Family/Education" },
    ],
    tags: ["health", "education"],
    focus: "Health & schooling",
    root: "Family",
    icon: "family",
  },
  {
    title: "Finance",
    description: "Insurance packs, invoices, statements and proof-of-payment.",
    links: [
      { label: "Insurance documents", href: "Finance/Insurance" },
      { label: "Invoices & receipts", href: "Finance/Invoices", note: "Speechworks, reimbursements" },
      { label: "Statements & summaries", href: "Finance/Statements" },
    ],
    tags: ["money", "admin"],
    focus: "Policies, receipts, statements",
    root: "Finance",
    icon: "finance",
  },
  {
    title: "Housing",
    description: "Rental applications, property paperwork, inspection notes.",
    links: [{ label: "Property folder", href: "Housing/Property" }],
    tags: ["property", "rentals"],
    focus: "Applications & inspections",
    root: "Housing",
    icon: "home",
  },
  {
    title: "Personal",
    description: "IDs, planning docs, wellbeing trackers and travel plans.",
    links: [
      { label: "Admin & identity", href: "Personal/Admin" },
      { label: "Planning & travel", href: "Personal/Planning" },
      { label: "Wellbeing & biometrics", href: "Personal/Health" },
    ],
    tags: ["planning", "health"],
    focus: "IDs, wellbeing, travel",
    root: "Personal",
    icon: "personal",
  },
  {
    title: "Projects",
    description: "Active software builds plus the tools they depend on.",
    links: [
      { label: "Projects/Software", href: "Projects/Software" },
      { label: "Tools & SDKs", href: "Projects/Software/Tools" },
    ],
    tags: ["code", "builds"],
    focus: "Active builds & tooling",
    root: "Projects",
    icon: "projects",
  },
  {
    title: "Hobbies",
    description: "Games, launchers, modding utilities and tabletop campaigns.",
    links: [
      { label: "Gaming", href: "Hobbies/Gaming" },
      { label: "Modding utilities", href: "Hobbies/Gaming/Modding" },
      { label: "Tabletop & D&D", href: "Hobbies/Tabletop" },
    ],
    tags: ["fun", "tabletop", "gaming"],
    focus: "Games & campaigns",
    root: "Hobbies",
    icon: "hobbies",
  },
  {
    title: "Media",
    description: "Photos, scans and screenshot captures.",
    links: [
      { label: "Photos", href: "Media/Photos" },
      { label: "Screenshots", href: "Media/Screenshots" },
    ],
    tags: ["photos", "screenshots"],
    focus: "Photos & screen captures",
    root: "Media",
    icon: "media",
  },
  {
    title: "Templates & Resources",
    description: "Reusable templates plus evergreen reference material.",
    links: [
      { label: "Templates", href: "Templates" },
      { label: "Resources", href: "Resources" },
    ],
    tags: ["reference"],
    focus: "Reusable content",
    root: "Templates",
    icon: "templates",
  },
  {
    title: "Archive",
    description: "Closed projects and historical records grouped by year.",
    links: [{ label: "Browse Archive", href: "Archive" }],
    tags: ["history", "records"],
    focus: "Historical snapshots",
    root: "Archive",
    icon: "archive",
  },
];

window.LIFEHUB_DATA.tasks = [
  { id: "downloads", label: "Empty Downloads → Inbox", cadence: "Weekly" },
  { id: "inbox", label: "File Inbox items into folders", cadence: "Weekly" },
  { id: "tags", label: "Apply macOS tags for cross-cutting topics", cadence: "Weekly" },
  { id: "projects", label: "Review active Projects for blockers", cadence: "Weekly" },
  { id: "archive", label: "Move closed work to Archive/YYYY", cadence: "Quarterly" },
];
