#!/usr/bin/env python3
"""Embed frequently-read dashboard JSON/text feeds into a single JS include.

When the dashboard loads via file://, Chrome blocks fetch/XHR calls to other
local files. This script snapshots key feeds into dashboard-inline-data.js so
the UI can hydrate without spinning up a local server.
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any, Dict, Optional

from lib.backup_targets import compute_backup_status, load_backup_logs, load_backup_targets

ROOT = Path(__file__).resolve().parent.parent


def read_json(path: Path) -> Optional[Any]:
  try:
    with path.open("r", encoding="utf-8") as handle:
      return json.load(handle)
  except FileNotFoundError:
    return None


def read_text(path: Path) -> Optional[str]:
  try:
    return path.read_text(encoding="utf-8")
  except FileNotFoundError:
    return None


def build_inline_payload() -> Dict[str, Any]:
  payload = {
    "stats": read_json(ROOT / "dashboard-stats.json"),
    "wellbeing": read_json(ROOT / "welltory-summary.json"),
    "recentFiles": read_json(ROOT / "recent-files.json"),
    "downloadsFeed": read_json(ROOT / "downloads-feed.json"),
    "agendaReminders": read_json(ROOT / "agenda-reminders.json"),
    "automationHistory": read_json(ROOT / "automation/logs/history.json"),
    "calendarIcs": read_text(ROOT / "Resources/calendar.ics"),
  }
  try:
    targets = load_backup_targets(ROOT / "automation/backups/targets.json")
    logs = load_backup_logs(ROOT / "automation/backups/status.json")
    backups = compute_backup_status(targets, logs)
    if backups:
      payload["backups"] = backups
  except FileNotFoundError:
    pass
  search_index = read_json(ROOT / "search-index.json")
  if search_index:
    payload["searchIndex"] = search_index[:500]
  return {key: value for key, value in payload.items() if value is not None}


def write_inline_file(data: Dict[str, Any]) -> None:
  output_path = ROOT / "dashboard-inline-data.js"
  with output_path.open("w", encoding="utf-8") as handle:
    handle.write("// Auto-generated by scripts/build_dashboard_inline_data.py\n")
    handle.write("window.LIFEHUB_INLINE_DATA = ")
    json.dump(data, handle, ensure_ascii=True, indent=2)
    handle.write(";\n")


def main() -> None:
  inline_payload = build_inline_payload()
  write_inline_file(inline_payload)
  print(f"Wrote inline snapshot with keys: {', '.join(sorted(inline_payload.keys())) or 'none'}")


if __name__ == "__main__":
  main()
